In [ ]:
# !unzip data.zip -d '/content/drive/Shareddrives/Python Scientists/Islam/Liver Disease/input'

In [1]:
#loading dataset
import pandas as pd
import numpy as np
#visualisation
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
#EDA
from collections import Counter
import pandas_profiling as pp
# data preprocessing
from sklearn.preprocessing import StandardScaler
# data splitting
from sklearn.model_selection import train_test_split
# data modeling
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
#ensembling
from mlxtend.classifier import StackingCVClassifier

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


In [5]:
data=pd.read_csv('/content/drive/Shareddrives/Python Scientists/Islam/Liver Disease/input/indian_liver_patient.csv')
data[data['Dataset']==1].head()

Age  Gender  Total_Bilirubin  ...  Albumin  Albumin_and_Globulin_Ratio  Dataset
0   65  Female              0.7  ...      3.3                        0.90        1
1   62    Male             10.9  ...      3.2                        0.74        1
2   62    Male              7.3  ...      3.3                        0.89        1
3   58    Male              1.0  ...      3.4                        1.00        1
4   72    Male              3.9  ...      2.4                        0.40        1

[5 rows x 11 columns]

In [ ]:
col_names = data.drop(['Gender'], axis=1).columns
col_names

Index(['Age', 'Total_Bilirubin', 'Direct_Bilirubin', 'Alkaline_Phosphotase',
       'Alamine_Aminotransferase', 'Aspartate_Aminotransferase',
       'Total_Protiens', 'Albumin', 'Albumin_and_Globulin_Ratio', 'Dataset'],
      dtype='object')

In [ ]:
data = data[[col for col in col_names] + ['Gender']]
data.head()

Age  Total_Bilirubin  ...  Dataset  Gender
0   65              0.7  ...        1  Female
1   62             10.9  ...        1    Male
2   62              7.3  ...        1    Male
3   58              1.0  ...        1    Male
4   72              3.9  ...        1    Male

[5 rows x 11 columns]

In [ ]:
data.info() # should help us to locate if there are any missing or null values


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         583 non-null    int64  
 1   Total_Bilirubin             583 non-null    float64
 2   Direct_Bilirubin            583 non-null    float64
 3   Alkaline_Phosphotase        583 non-null    int64  
 4   Alamine_Aminotransferase    583 non-null    int64  
 5   Aspartate_Aminotransferase  583 non-null    int64  
 6   Total_Protiens              583 non-null    float64
 7   Albumin                     583 non-null    float64
 8   Albumin_and_Globulin_Ratio  579 non-null    float64
 9   Dataset                     583 non-null    int64  
 10  Gender                      583 non-null    object 
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB


In [ ]:
# checking the stats
# given in the website 416 liver disease patients and 167 non liver disease patients
# need to remap the classes liver disease:=1 and no liver disease:=0 (normal convention to be followed)
count_classes = pd.value_counts(data['Dataset'], sort = True).sort_index()
count_classes.plot(kind = 'bar')
plt.title("Liver disease classes histogram")
plt.xlabel("Dataset")
plt.ylabel("Frequency")


Text(0, 0.5, 'Frequency')

In [ ]:
data['Dataset'] = data['Dataset'].map({2:0,1:1}) 
data['Gender'] = data['Gender'].map({'Male':0, 'Female':1}) 

In [ ]:
data['Dataset'].value_counts()

1    416
0    167
Name: Dataset, dtype: int64

In [ ]:
data['Albumin_and_Globulin_Ratio'].fillna(value=0, inplace=True)

In [3]:
data[data['Dataset']==0].head()

Empty DataFrame
Columns: [Age, Gender, Total_Bilirubin, Direct_Bilirubin, Alkaline_Phosphotase, Alamine_Aminotransferase, Aspartate_Aminotransferase, Total_Protiens, Albumin, Albumin_and_Globulin_Ratio, Dataset]
Index: []

In [ ]:
data_features=data.drop(['Dataset'],axis=1)
data_num_features=data.drop(['Gender','Dataset'],axis=1)
data_num_features.head()


Age  Total_Bilirubin  ...  Albumin  Albumin_and_Globulin_Ratio
0   65              0.7  ...      3.3                        0.90
1   62             10.9  ...      3.2                        0.74
2   62              7.3  ...      3.3                        0.89
3   58              1.0  ...      3.4                        1.00
4   72              3.9  ...      2.4                        0.40

[5 rows x 9 columns]

In [ ]:
data_num_features.describe() # check to whether feature scaling has to be performed or not 


Age  Total_Bilirubin  ...     Albumin  Albumin_and_Globulin_Ratio
count  583.000000       583.000000  ...  583.000000                  583.000000
mean    44.746141         3.298799  ...    3.141852                    0.940566
std     16.189833         6.209522  ...    0.795519                    0.327962
min      4.000000         0.400000  ...    0.900000                    0.000000
25%     33.000000         0.800000  ...    2.600000                    0.700000
50%     45.000000         1.000000  ...    3.100000                    0.920000
75%     58.000000         2.600000  ...    3.800000                    1.100000
max     90.000000        75.000000  ...    5.500000                    2.800000

[8 rows x 9 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
cols=list(data_num_features.columns)
data_features_scaled=pd.DataFrame(data=data_features)
data_features_scaled[cols]=scaler.fit_transform(data_features[cols])
data_features_scaled.head()


Age  Total_Bilirubin  ...  Albumin_and_Globulin_Ratio  Gender
0  1.252098        -0.418878  ...                   -0.123797       1
1  1.066637         1.225171  ...                   -0.612077       0
2  1.066637         0.644919  ...                   -0.154315       0
3  0.819356        -0.370523  ...                    0.181378       0
4  1.684839         0.096902  ...                   -1.649672       0

[5 rows x 10 columns]

In [ ]:
data_exp=data_features_scaled
data_exp.head()

Age  Total_Bilirubin  ...  Albumin_and_Globulin_Ratio  Gender
0  1.252098        -0.418878  ...                   -0.123797       1
1  1.066637         1.225171  ...                   -0.612077       0
2  1.066637         0.644919  ...                   -0.154315       0
3  0.819356        -0.370523  ...                    0.181378       0
4  1.684839         0.096902  ...                   -1.649672       0

[5 rows x 10 columns]

In [ ]:
# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(12, 10))
plt.title('Pearson Correlation of liver disease Features')
# Draw the heatmap using seaborn
sns.heatmap(data_num_features.astype(float).corr(),linewidths=0.25,vmax=1.0, square=True, cmap="YlGnBu", linecolor='black',annot=True)


In [ ]:
X=data_exp
y=data['Dataset'] 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
X.head()

Age  Total_Bilirubin  ...  Albumin_and_Globulin_Ratio  Gender
0  1.252098        -0.418878  ...                   -0.123797       1
1  1.066637         1.225171  ...                   -0.612077       0
2  1.066637         0.644919  ...                   -0.154315       0
3  0.819356        -0.370523  ...                    0.181378       0
4  1.684839         0.096902  ...                   -1.649672       0

[5 rows x 10 columns]

In [ ]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Dataset, dtype: int64

In [ ]:
m1 = 'Logistic Regression'
lr = LogisticRegression()
model = lr.fit(X_train, y_train)
lr_predict = lr.predict(X_test)
lr_conf_matrix = confusion_matrix(y_test, lr_predict)
lr_acc_score = accuracy_score(y_test, lr_predict)
print("confussion matrix")
print(lr_conf_matrix)
print("\n")
print("Accuracy of Logistic Regression:",lr_acc_score*100,'\n')
print(classification_report(y_test,lr_predict))

confussion matrix
[[  9  44]
 [ 11 111]]


Accuracy of Logistic Regression: 68.57142857142857 

              precision    recall  f1-score   support

           0       0.45      0.17      0.25        53
           1       0.72      0.91      0.80       122

    accuracy                           0.69       175
   macro avg       0.58      0.54      0.52       175
weighted avg       0.64      0.69      0.63       175



In [ ]:
m2 = 'Naive Bayes'
nb = GaussianNB()
nb.fit(X_train,y_train)
nbpred = nb.predict(X_test)
nb_conf_matrix = confusion_matrix(y_test, nbpred)
nb_acc_score = accuracy_score(y_test, nbpred)
print("confussion matrix")
print(nb_conf_matrix)
print("\n")
print("Accuracy of Naive Bayes model:",nb_acc_score*100,'\n')
print(classification_report(y_test,nbpred))

confussion matrix
[[53  0]
 [75 47]]


Accuracy of Naive Bayes model: 57.14285714285714 

              precision    recall  f1-score   support

           0       0.41      1.00      0.59        53
           1       1.00      0.39      0.56       122

    accuracy                           0.57       175
   macro avg       0.71      0.69      0.57       175
weighted avg       0.82      0.57      0.57       175



In [ ]:
m3 = 'Random Forest Classfier'
rf = RandomForestClassifier(n_estimators=20, random_state=2,max_depth=5)
rf.fit(X_train,y_train)
rf_predicted = rf.predict(X_test)
rf_conf_matrix = confusion_matrix(y_test, rf_predicted)
rf_acc_score = accuracy_score(y_test, rf_predicted)
print("confussion matrix")
print(rf_conf_matrix)
print("\n")
print("Accuracy of Random Forest:",rf_acc_score*100,'\n')
print(classification_report(y_test,rf_predicted))

confussion matrix
[[  6  47]
 [  9 113]]


Accuracy of Random Forest: 68.0 

              precision    recall  f1-score   support

           0       0.40      0.11      0.18        53
           1       0.71      0.93      0.80       122

    accuracy                           0.68       175
   macro avg       0.55      0.52      0.49       175
weighted avg       0.61      0.68      0.61       175



In [ ]:
m4 = 'Extreme Gradient Boost'
xgb = XGBClassifier(learning_rate=0.01, n_estimators=25, max_depth=15,gamma=0.6, subsample=0.52,colsample_bytree=0.6,seed=27, 
                    reg_lambda=2, booster='dart', colsample_bylevel=0.6, colsample_bynode=0.5)
xgb.fit(X_train, y_train)
xgb_predicted = xgb.predict(X_test)
xgb_conf_matrix = confusion_matrix(y_test, xgb_predicted)
xgb_acc_score = accuracy_score(y_test, xgb_predicted)
print("confussion matrix")
print(xgb_conf_matrix)
print("\n")
print("Accuracy of Extreme Gradient Boost:",xgb_acc_score*100,'\n')
print(classification_report(y_test,xgb_predicted))

confussion matrix
[[  1  52]
 [  0 122]]


Accuracy of Extreme Gradient Boost: 70.28571428571428 

              precision    recall  f1-score   support

           0       1.00      0.02      0.04        53
           1       0.70      1.00      0.82       122

    accuracy                           0.70       175
   macro avg       0.85      0.51      0.43       175
weighted avg       0.79      0.70      0.59       175



In [ ]:
m5 = 'K-NeighborsClassifier'
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train, y_train)
knn_predicted = knn.predict(X_test)
knn_conf_matrix = confusion_matrix(y_test, knn_predicted)
knn_acc_score = accuracy_score(y_test, knn_predicted)
print("confussion matrix")
print(knn_conf_matrix)
print("\n")
print("Accuracy of K-NeighborsClassifier:",knn_acc_score*100,'\n')
print(classification_report(y_test,knn_predicted))

confussion matrix
[[ 10  43]
 [ 21 101]]


Accuracy of K-NeighborsClassifier: 63.42857142857142 

              precision    recall  f1-score   support

           0       0.32      0.19      0.24        53
           1       0.70      0.83      0.76       122

    accuracy                           0.63       175
   macro avg       0.51      0.51      0.50       175
weighted avg       0.59      0.63      0.60       175



In [ ]:
m6 = 'DecisionTreeClassifier'
dt = DecisionTreeClassifier(criterion = 'entropy',random_state=42,max_depth = 6)
dt.fit(X_train, y_train)
dt_predicted = dt.predict(X_test)
dt_conf_matrix = confusion_matrix(y_test, dt_predicted)
dt_acc_score = accuracy_score(y_test, dt_predicted)
print("confussion matrix")
print(dt_conf_matrix)
print("\n")
print("Accuracy of DecisionTreeClassifier:",dt_acc_score*100,'\n')
print(classification_report(y_test,dt_predicted))

confussion matrix
[[  7  46]
 [ 15 107]]


Accuracy of DecisionTreeClassifier: 65.14285714285715 

              precision    recall  f1-score   support

           0       0.32      0.13      0.19        53
           1       0.70      0.88      0.78       122

    accuracy                           0.65       175
   macro avg       0.51      0.50      0.48       175
weighted avg       0.58      0.65      0.60       175



In [ ]:
m7 = 'Support Vector Classifier'
svc =  SVC(kernel='rbf', C=2)
svc.fit(X_train, y_train)
svc_predicted = svc.predict(X_test)
svc_conf_matrix = confusion_matrix(y_test, svc_predicted)
svc_acc_score = accuracy_score(y_test, svc_predicted)
print("confussion matrix")
print(svc_conf_matrix)
print("\n")
print("Accuracy of Support Vector Classifier:",svc_acc_score*100,'\n')
print(classification_report(y_test,svc_predicted))

confussion matrix
[[  3  50]
 [  8 114]]


Accuracy of Support Vector Classifier: 66.85714285714286 

              precision    recall  f1-score   support

           0       0.27      0.06      0.09        53
           1       0.70      0.93      0.80       122

    accuracy                           0.67       175
   macro avg       0.48      0.50      0.45       175
weighted avg       0.57      0.67      0.58       175



In [ ]:
# TODO: Import 'GridSearchCV', 'make_scorer', and any other necessary libraries
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer, fbeta_score,accuracy_score
from sklearn.ensemble import RandomForestClassifier
# TODO: Initialize the classifier
clf = RandomForestClassifier(random_state=0)

# TODO: Create the parameters list you wish to tune, using a dictionary if needed.
# HINT: parameters = {'parameter_1': [value1, value2], 'parameter_2': [value1, value2]}
parameters = {'n_estimators': [100,250,500], 'max_depth': [3,6,9]}

# TODO: Make an fbeta_score scoring object using make_scorer()
scorer = make_scorer(fbeta_score,beta=2)

# TODO: Perform grid search on the classifier using 'scorer' as the scoring method using GridSearchCV()
grid_obj = GridSearchCV(clf,parameters,scoring=scorer,n_jobs=-1)

# TODO: Fit the grid search object to the training data and find the optimal parameters using fit()
grid_fit = grid_obj.fit(X_train,y_train)

# Get the estimator
best_clf = grid_fit.best_estimator_

# Make predictions using the unoptimized and model
predictions = (clf.fit(X_train,y_train)).predict(X_test)
best_predictions = best_clf.predict(X_test)

In [ ]:
m8 = 'GridSearchCV Random Forest Classfier'
best_clf.fit(X_train,y_train)
clf_predicted = best_clf.predict(X_test)
clf_conf_matrix = confusion_matrix(y_test, clf_predicted)
clf_acc_score = accuracy_score(y_test, clf_predicted)
print("confussion matrix")
print(rf_conf_matrix)
print("\n")
print("Accuracy of Random Forest:",clf_acc_score*100,'\n')
print(classification_report(y_test,clf_predicted))

confussion matrix
[[  6  47]
 [  9 113]]


Accuracy of Random Forest: 70.28571428571428 

              precision    recall  f1-score   support

           0       0.57      0.08      0.13        53
           1       0.71      0.98      0.82       122

    accuracy                           0.70       175
   macro avg       0.64      0.53      0.48       175
weighted avg       0.67      0.70      0.61       175



In [ ]:
model_ev = pd.DataFrame({'Model': ['Logistic Regression','Naive Bayes','Random Forest','Extreme Gradient Boost',
                    'K-Nearest Neighbour','Decision Tree','Support Vector Machine', 'GridSearchCV Random Forest'], 'Accuracy': [lr_acc_score*100,
                    nb_acc_score*100,rf_acc_score*100,xgb_acc_score*100,knn_acc_score*100,dt_acc_score*100,svc_acc_score*100,clf_acc_score*100]})
model_ev

Model   Accuracy
0         Logistic Regression  68.571429
1                 Naive Bayes  57.142857
2               Random Forest  68.000000
3      Extreme Gradient Boost  70.285714
4         K-Nearest Neighbour  63.428571
5               Decision Tree  65.142857
6      Support Vector Machine  66.857143
7  GridSearchCV Random Forest  70.285714

In [ ]:
import lightgbm as lgb
clf = lgb.LGBMClassifier()
clf.fit(X_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
y_pred=clf.predict(X_test)


In [ ]:
# view accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred, y_test)
print('LightGBM Model accuracy score: {0:0.4f}'.format(accuracy_score(y_test, y_pred)))


LightGBM Model accuracy score: 0.6857


In [ ]:
y_pred_train = clf.predict(X_train)


In [ ]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))


Training-set accuracy score: 1.0000


In [ ]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(clf.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(clf.score(X_test, y_test)))


Training set score: 1.0000
Test set score: 0.6857


In [ ]:
# view confusion-matrix
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n', cm)
print('\nTrue Positives(TP) = ', cm[0,0])
print('\nTrue Negatives(TN) = ', cm[1,1])
print('\nFalse Positives(FP) = ', cm[0,1])
print('\nFalse Negatives(FN) = ', cm[1,0])


Confusion matrix

 [[ 18  35]
 [ 20 102]]

True Positives(TP) =  18

True Negatives(TN) =  102

False Positives(FP) =  35

False Negatives(FN) =  20


In [ ]:
# visualize confusion matrix with seaborn heatmap

cm_matrix = pd.DataFrame(data=cm, columns=['Actual Positive:1', 'Actual Negative:0'], 
                                 index=['Predict Positive:1', 'Predict Negative:0'])

sns.heatmap(cm_matrix, annot=True, fmt='d', cmap='YlGnBu')


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.47      0.34      0.40        53
           1       0.74      0.84      0.79       122

    accuracy                           0.69       175
   macro avg       0.61      0.59      0.59       175
weighted avg       0.66      0.69      0.67       175



In [ ]:
import pickle

# Save scaler
filename = 'scaler.bin'
pickle.dump(scaler, open(filename, 'wb'))

# Save model
filename = 'liver-disease-70.pkl'
pickle.dump(best_clf, open(filename, 'wb'))

In [ ]:
import pickle

def predict(path_to_model, path_to_scaler, Age, Total_Bilirubin, Direct_Bilirubin, Alkaline_Phosphotase, Alamine_Aminotransferase, Aspartate_Aminotransferase, Total_Protiens, Albumin, Albumin_and_Globulin_Ratio, Gender):
    X1 = np.array([[Age, Total_Bilirubin, Direct_Bilirubin, Alkaline_Phosphotase, Alamine_Aminotransferase, Aspartate_Aminotransferase, Total_Protiens, Albumin, Albumin_and_Globulin_Ratio]])
    X2 = np.array([[Gender]])
    model = pickle.load(open(path_to_model, 'rb'))
    scaler = pickle.load(open(path_to_scaler, 'rb'))
    X1 = scaler.transform(X1)
    print(X1)
    X = np.hstack((X1, X2))
    result = model.predict(X)
    return result

path_to_model = '/content/drive/Shareddrives/Python Scientists/Islam/Liver Disease/model/liver-disease-70.pkl'
path_to_scaler = '/content/drive/Shareddrives/Python Scientists/Islam/Liver Disease/scaler/scaler.bin'
# predict(path_to_model, path_to_scaler, 17,	0.9,	0.3,	202,	22,	19,	7.4,	4.1,	1.20, 0)
predict(path_to_model, path_to_scaler, 65,		0.7,	0.1,	187,	16,	18,	6.8,	3.3,	0.90, 1)

[[ 1.25209764 -0.41887783 -0.49396398 -0.42671496 -0.35466541 -0.31839333
   0.29211961  0.19896867 -0.12379736]]


array([1])